#!/bin/bash

function launchTests
{
	phpunit $2 --syntax-check --bootstrap tests/bootstrap.php $1
}

function launchAllTests
{
	launchTests tests/ $1
}

case $1 in
	test)
		if [ -z $2 ]
		    then
			launchAllTests
		else
			launchTests $2
		fi
		;;
	*)
		echo "Usage: restapp COMMAND"
		echo "COMMAND:"
		echo "	test [PATH_TO_TEST_FILE]	runs unit tests"
		;;
esac
