#!/bin/bash

function launchTests
{
	phpunit $2 --syntax-check --bootstrap tests/bootstrap.php --exclude-group autoload $1
}

function launchAutoloadsTests
{
	phpunit $1 --syntax-check --bootstrap tests/bootstrapnoautoload.php tests/unit/library/simplerest/AutoloaderTest.php
}

function launchAllTests
{
	launchTests tests/
	launchAutoloadsTests
}

case $1 in
	test)
		if [ -z $2 ]
		    then
			launchAllTests
		else
			launchTests $2
		fi
		;;
	*)
		echo "Usage: restapp COMMAND"
		echo "COMMAND:"
		echo "	test [PATH_TO_TEST_FILE]	runs unit tests"
		;;
esac
