#!/bin/sh
case $1 in
	test)
		if [ -z $2 ]
		then
			phpunit --bootstrap tests/bootstrap.php tests
		else
			phpunit --bootstrap tests/bootstrap.php $2
		fi
		;;
	*)
		echo "Usage: restapp COMMAND"
		echo "COMMAND:"
		echo "	test [PATH_TO_TEST_FILE]	runs unit tests"
		;;
esac
