#!/bin/bash

function launchTests
{
	phpunit $2 --syntax-check --bootstrap test/bootstrap.php --exclude-group autoload $1
}


function launchAutoloadsTests
{
	phpunit $1 --syntax-check --bootstrap test/bootstrapnoautoload.php test/unit/library/simplerest/AutoloaderTest.php
}

function launchAllTests
{
	launchTests test/functional
	launchTests test/unit
	launchAutoloadsTests
}

case $1 in
	test:autoloader)
		launchAutoloadsTests
		;;
	test:all)
		launchAllTests
		;;
	test:functional)
		launchTests test/functional
		;;
	test)
		if [ -z $2 ]
		    then
			launchTests test/unit
		else
			launchTests $2
		fi
		;;
	*)
		echo "Usage: restapp COMMAND"
		echo "COMMAND:"
		echo "	test [PATH_TO_TEST_FILE]	runs unit tests"
		echo "	test:functional				runs functional tests"
		echo "	test:autoloader				runs autoloader tests"
		echo "	test:all					runs all tests"
		;;
esac
